# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for Sony PlayStation 4 platform drivers
#
obj-$(CONFIG_PS4_APCIE)		+= ps4-apcie.o
obj-$(CONFIG_PS4_APCIE)		+= ps4-apcie-icc.o
obj-$(CONFIG_PS4_APCIE)		+= ps4-apcie-uart.o
obj-$(CONFIG_PS4_APCIE)		+= ps4-apcie-pwrbutton.o
obj-$(CONFIG_PS4_APCIE)		+= icc/i2c.o
obj-$(CONFIG_PS4_FAN) += ps4-fan.o
obj-$(CONFIG_PS4_LED) += ps4-led.o
obj-$(CONFIG_PS4_BUZZER)	+= ps4-buzzer.o
